version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/my_app_dir 
    ports:
      - "8000:8000"
    depends_on:
      - db
  #mysql:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zeitplan
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    volumes:
      - ../mysql:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080