# Generated by Django 3.2 on 2022-09-27 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoaulahorario',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.aula'),
        ),
        migrations.AlterField(
            model_name='estadogradohorario',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.grado'),
        ),
        migrations.AlterField(
            model_name='estadomateriahorario',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.materia'),
        ),
        migrations.AlterField(
            model_name='estadoprofesorhorario',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.profesor'),
        ),
    ]
