# Generated by Django 3.2 on 2022-09-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20220927_0750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materia',
            old_name='state',
            new_name='status_model',
        ),
        migrations.AddField(
            model_name='grado',
            name='status_model',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='status_model',
            field=models.BooleanField(default=True),
        ),
    ]
